version: '3.5'

services:
  app:
    build: .
    expose:
      - "4000"
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - MIX_ENV=dev
    volumes:
      - .:/home/app
    working_dir: /home/app
