version: '3.5'

services:
  app:
    image: bitwalker/alpine-elixir-phoenix:1.8.1
    expose:
      - "4000"
    ports:
      - "4000:4000"
    env_file:
      - env/docker.env
    volumes:
      - .:/home/app
    working_dir: /home/app
